### ISSUE TITLE
onverting overloaded function 'delay' to type 'LaCrosse_TX23::DelayFunc' {aka 'void (*)(unsigned int)'} is ambiguous

### ISSUE THREAD

**Issue by SeByDocKy** [egzumer/Arduino-LaCrosse-TX23-Library#1]
Hi,

I just trying to recompile my ESPhome custom sensor for ESP32 based on your lib. It used to work perfectly just before the last PR. Now I got the following error ; 
src/tx23_custom_sensor.h:19:51: error: converting overloaded function 'delay' to type 'LaCrosse_TX23::DelayFunc' {aka 'void (*)(unsigned int)'} is ambiguous

I guess it's more related to plateformio/ESP32 but you have to know a lot of users use ESP chip instead or arduino.

Here is the .h file I am using to link with your lib:

```
#include "esphome.h"
#include "LaCrosse_TX23.h"
#include "esphome/core/version.h"

/*
#if ESPHOME_VERSION_CODE >= VERSION_CODE(2021, 10, 0)
#define DELAY delay
#else
#define DELAY delay
#endif
*/

#define DATAPIN 2
#define OFFSET_TX23 90.0

class TX23CustomSensor : public PollingComponent, public Sensor 
{
 public:
  LaCrosse_TX23 anemometer = LaCrosse_TX23(DATAPIN);
  Sensor *speed_sensor = new Sensor();
  Sensor *direction_sensor = new Sensor();
  TX23CustomSensor() : PollingComponent(2500) {}
  void setup() override {
	  
	  pinMode(DATAPIN, OUTPUT);
	  digitalWrite(DATAPIN,LOW);
	  //delay(5000);
	//  esphome::delay(5000);
	//  DELAY(5000);
	  digitalWrite(DATAPIN,HIGH);
	  pinMode(DATAPIN, INPUT);
  }
  void update() override {
	static const char *dirTable[] = {"N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"};
	float speed;
//	float direction;
	uint16_t direction;
	bool reading;
	
	reading = anemometer.read(speed, direction);
    //if(reading)  
	//if(anemometer.read(speed, direction))
		
	speed_sensor->publish_state(speed);
	//direction_sensor->publish_state(direction*22.5);
	direction_sensor->publish_state(  float( ( (direction*22.5) + OFFSET_TX23) - 360.0*int(((direction*22.5) + OFFSET_TX23)/360.0) )   );
	
    ESP_LOGD("custom", "reading is: %d", reading);
    ESP_LOGD("custom", "speed is: %3.2f", speed);
	ESP_LOGD("custom", "direction is: %s", dirTable[direction]);
	
  }
};
````

**Comment by egzumer** [comment]
Sorry for the trouble, this should fix this. Also note that read function changed, there are multiple overloaded functions now, and the one that you use will probably return wind direction 0-359 instead of 0-15.

**Comment by SeByDocKy** [comment]
> Sorry for the trouble, this should fix this. Also note that read function changed, there are multiple overloaded functions now, and the one that you use will probably return wind direction 0-359 instead of 0-15.

Now got another error :(


```/data/station_meteo/.piolibdeps/station_meteo/La Crosse RX23 Library/LaCrosse_TX23.h:33:27: error: decltype cannot resolve address of overloaded function```

**Comment by egzumer** [comment]
Weird, delay is overloaded? This one should work now.

**Comment by SeByDocKy** [comment]
Compiling fine now :) Thx a lot :)....
