### ISSUE TITLE
Error: cannot bind non-const lvalue reference of type 'uint16_t&' {aka 'short unsigned int&'} to an rvalue of type 'uint16_t' {aka 'short unsigned int'}

### ISSUE THREAD

**Issue by psycmos** [egzumer/Arduino-LaCrosse-TX23-Library#2]
Compiling /data/central_vento/.pioenvs/central_vento/lib29f/La Crosse RX23 Library/LaCrosse_TX23.cpp.o
In file included from src/main.cpp:30:
src/tx23_custom_sensor.h: In member function 'virtual void TX23CustomSensor::update()':
src/tx23_custom_sensor.h:25:35: error: cannot bind non-const lvalue reference of type 'uint16_t&' {aka 'short unsigned int&'} to an rvalue of type 'uint16_t' {aka 'short unsigned int'}
  reading = anemometer.read(speed, direction);
                                   ^~~~~~~~~
In file included from src/tx23_custom_sensor.h:2,
                 from src/main.cpp:30:
/data/central_vento/.piolibdeps/central_vento/La Crosse RX23 Library/LaCrosse_TX23.h:41:10: note:   initializing argument 2 of 'bool LaCrosse_TX23::read(float&, uint16_t&)'
     bool read(float &speed, uint16_t &direction);
          ^~~~
          
          
 *** [/data/central_vento/.pioenvs/central_vento/src/main.cpp.o] Error 1
 
 
 
 
 I can´t compile it, i try it using it ESP compiler in homeassistant

**Comment by egzumer** [comment]
There seems to be some problem with type of variables that you define and try to **pass** to the read function. How does the code that you try to run look like?

**Comment by psycmos** [comment]
MY Yaml is

esphome:
  name: central_vento
  platform: ESP32
  board: nodemcu-32s
  includes:
    - tx23_custom_sensor.h
  libraries:
    - "https://github.com/egzumer/Arduino-LaCrosse-TX23-Library"
 
sensor:

  - platform: custom
    id: tx23_id
    lambda: |-
      auto TX23 = new TX23CustomSensor();
      App.register_component(TX23);
      return {TX23->speed_sensor, TX23->direction_sensor};

    sensors:
    - name: "Velocidade do vento"
      unit_of_measurement: "m/s"
      accuracy_decimals: 1
      icon: "mdi:weather-windy"
    
    - name: "Direcção do vento"
      unit_of_measurement: "°"
      icon: "mdi:compass-outline"

**Comment by psycmos** [comment]
I used the tx23_custom_sensor.h


#include "esphome.h"
#include "LaCrosse_TX23.h"

#define DATAPIN 2

class TX23CustomSensor : public PollingComponent, public Sensor {
 public:
  LaCrosse_TX23 anemometer = LaCrosse_TX23(DATAPIN);
  Sensor *speed_sensor = new Sensor();
  Sensor *direction_sensor = new Sensor();
  TX23CustomSensor() : PollingComponent(3000) {}
  void setup() override {
	  
	  pinMode(DATAPIN, OUTPUT);
	  digitalWrite(DATAPIN,LOW);
	  delay(1000);
	  pinMode(DATAPIN, INPUT);
  }
  void update() override {
	static const char *dirTable[] = {"N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"};
	float speed;
	int direction;
	bool reading;
	
	reading = anemometer.read(speed, direction);
    //if(reading)  
	//if(anemometer.read(speed, direction))
		
	speed_sensor->publish_state(speed);
	//direction_sensor->publish_state(direction*22.5);
	direction_sensor->publish_state(  ( (direction*22.5) + 90.0) - 360.0*int(((direction*22.5) + 90.0)/360.0)    );
	
    ESP_LOGD("custom", "reading is: %d", reading);
    ESP_LOGD("custom", "speed is: %3.2f", speed);
	ESP_LOGD("custom", "direction is: %s", dirTable[direction]);
	
  }
};

**Comment by psycmos** [comment]
I compiled it in 2022 and it works well, i have not changed nothing in my code.

**Comment by egzumer** [comment]
There seems to be more people using this library than I thought :). Sorry I pushed some braking changes, the read function works a bit different now. The direction has to be uint16_t, not int. And the return value is in degrees and not a value 0-16. You have to modify your code.

**Comment by psycmos** [comment]
Thanks a lot  for your support @egzumer .
I have no sufficient know how to do that! :(
Buy i will try!

If you can help us with your know-how upgrading this tx23_custom_sensor.h !
That will be great!!! Maybe will help other users like me 👯‍♂️

**Comment by egzumer** [comment]
`int direction;` 
change to 
`uint16_t direction;`

`direction_sensor->publish_state(  ( (direction*22.5) + 90.0) - 360.0*int(((direction*22.5) + 90.0)/360.0)    );`
to
`direction_sensor->publish_state(  (direction + 90.0) - 360.0*int((direction + 90.0)/360.0)    );`

remove:
`ESP_LOGD("custom", "direction is: %s", dirTable[direction]);`

**Comment by psycmos** [comment]
Thanks a lot my @egzumer It works!!! :D
