### ISSUE TITLE
error: cannot bind non-const lvalue reference of type 'uint16_t&'

### ISSUE THREAD

**Issue by T0RST3N** [egzumer/Arduino-LaCrosse-TX23-Library#4]
Hello,

I cannot compile my TX23 sensor in homeassistant with ESPHome.
I get this error here. Unfortunately I have no idea about c++.

`In file included from src/main.cpp:39:
src/tx23_custom_sensor.h: In member function 'virtual void TX23CustomSensor::update()':
src/tx23_custom_sensor.h:21:35: error: cannot bind non-const lvalue reference of type 'uint16_t&' {aka 'short unsigned int&'} to an rvalue of type 'uint16_t' {aka 'short unsigned int'}
   21 |  reading = anemometer.read(speed, direction);
      |                                   ^~~~~~~~~
In file included from src/tx23_custom_sensor.h:2,
                 from src/main.cpp:39:
/data/esp-wetter/.piolibdeps/esp-wetter/La Crosse RX23 Library/LaCrosse_TX23.h:41:39: note:   initializing argument 2 of 'bool LaCrosse_TX23::read(float&, uint16_t&)'
   41 |     bool read(float &speed, uint16_t &direction);
      |                             ~~~~~~~~~~^~~~~~~~~
Compiling /data/esp-wetter/.pioenvs/esp-wetter/FrameworkArduino/MD5Builder.cpp.o
Compiling /data/esp-wetter/.pioenvs/esp-wetter/FrameworkArduino/Print.cpp.o
Compiling /data/esp-wetter/.pioenvs/esp-wetter/FrameworkArduino/Schedule.cpp.o
*** [/data/esp-wetter/.pioenvs/esp-wetter/src/main.cpp.o] Error 1
![tx23](https://user-images.githubusercontent.com/25604832/234779846-3d30ccdf-6552-47f0-88da-12d438281610.jpg)

Thank You`

**Comment by egzumer** [comment]
Hi.
This should help, take a look at the last comment: #2

**Comment by T0RST3N** [comment]
Thank You,

Yes, the compilation is now OK.

but I do not get any measured values

The sensor worked, I had installed Tasmota before.
The sensor is connected to D5 GPIO14. I have changed DATAPIN to 14

this is my tx23_custom_senso.h


```
#include "esphome.h"
#include "LaCrosse_TX23.h"

#define DATAPIN 14

class TX23CustomSensor : public PollingComponent, public Sensor {
 public:
  LaCrosse_TX23 anemometer = LaCrosse_TX23(DATAPIN);
  Sensor *speed_sensor = new Sensor();
  Sensor *direction_sensor = new Sensor();
  TX23CustomSensor() : PollingComponent(3000) {}
  void setup() override {
      pinMode(DATAPIN, OUTPUT);
      digitalWrite(DATAPIN,LOW);
      delay(1000);
      pinMode(DATAPIN, INPUT);
  }
  void update() override {
	static const char *dirTable[] = {"N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"};
	float speed;
	uint16_t direction;
	bool reading;
	
	reading = anemometer.read(speed, direction);
   		
	speed_sensor->publish_state(speed);
	direction_sensor->publish_state(  (direction + 90.0) - 360.0*int((direction + 90.0)/360.0)    );
	
    ESP_LOGD("custom", "reading is: %d", reading);
    ESP_LOGD("custom", "speed is: %3.2f", speed);

  }
};
```

**Comment by egzumer** [comment]
Sometimes I had problem with the sensor not working. I had to disconnect and connect it again. Try doing that.

**Comment by T0RST3N** [comment]
Thank you very much,

I've checked everything again. Also the wiring. I noticed that I didn't have a 4.7k pull-up resistor between data and VCC. I quickly changed that and now it works.

Thanks again.

Greetings
