### ISSUE TITLE
BSD license clarification

### ISSUE THREAD

**Issue by KodinLanewave** [egzumer/Arduino-LaCrosse-TX23-Library#5]
Can you please clarify which BSD license version you are licensing this library under? I'm interested in integrating this into the Meshtastic project however only certain versions of BSD are compatible with GPL v3.  Thank you!

**Comment by egzumer** [comment]
I'm not good at licencing. Hope this claryfies it 52b07ae7518481be2097498de7e5c2242c3dfb1a
